name: CI
env:
  EB_package_s3_buket_name: "flask-packages"
  EB_app_name: "my-flask"
  EB_env_name: "myFlask_env"
  deploy_package_name: "flask_app${{ github.sha }}.zip"
  AWS_region_name: "rus"
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git clone repo
      - uses: actions/checout@v1 
      - name: create ZIP deploy package
        run: zip -r ${{ env.deploy_package_name }} ./ -x *.git*
      - name: configure my AWS Credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_region_name }}
          
      - name: copy deploy package
        run: aws s3 cp ${{ env.deploy_package_name }} s3://${{ env.EB_package_s3_buket_name }}/
  my_cD_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    steps:   
    - name: ggg
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.

